version: '3.4'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
      - ./penguin.jpg:/usr/share/nginx/html/penguin.jpg
    ports:
      - "888:80"